

services:
  nodo1:
    build: .
    container_name: nodo1
    environment:
      LISTEN_PORT: 9000
      PEER_HOST: nodo2
      PEER_PORT: 9001
    command: ["java", "Nodo", "9000", "nodo2", "9001"]
    networks:
      - nodos_net

  nodo2:
    build: .
    container_name: nodo2
    environment:
      LISTEN_PORT: 9001
      PEER_HOST: nodo1
      PEER_PORT: 9000
    command: ["java", "Nodo", "9001", "nodo1", "9000"]
    networks:
      - nodos_net

networks:
  nodos_net:
    driver: bridge