

services:
  servidor:
    build: .
    container_name: server
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - task-network

networks:
  task-network:
    name: task-network
    driver: bridge
    attachable: true
 
 
 
    
